merge_queue:
  max_parallel_checks: 1
queue_rules:
  - name: default
    batch_size: 1
    queue_conditions:
      - check-success = quarantine-gate
    merge_conditions:
      - check-success = quarantine-gate
